# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fizzbuzz',
            fields=[
                ('fizzbuzz_id', models.AutoField(primary_key=True, serialize=False)),
                ('useragent', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
    ]
